---
- hosts: appserver
  become: yes
  tasks: 
  - name: installing openjdk8 on redhat
    yum: 
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: Installing tomcat on redhat
    yum:
      name: tomcat
      state: present
  - name: Tomcat status
    service: 
      name: tomcat
      state: started
     enabled: yes 
  - name: Installing jenkins
    get_url:
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.89.3/jenkins.war
      dest: /usr/lib/systemd/system/tomcat/jenkins.war