---
- hosts: appserver
  become: yes
  tasks:
  - name: Install curl
    yum:
      name: curl
      state: present
  - name: enable nodejs
    uri: 
      url: https://rpm.nodesource.com/setup_8.x
  - name: Install nodejs
    yum:
      name: nodejs
      state: present
  - name: check version
    yum:
      name: node
  - name: update
    yum: 
      name: update
  