---
# tasks file for phanindra.apache
- name: install apache on debian
  apt:
    name: apache2
    state: present
  when: ansible_os_family=="Debian"
- name: install apache on redhat
  yum:
    name: httpd
    state: present
  when: ansible_os_family=="RedHat"
- name: set service name for debian
  set_fact:
    apache_package: "{{apache_package_deb}}" 
  when: ansible_os_family=="Debian"
- name: set service facts for RedHat
  set_fact:
    apache_package: "{{apache_package_rhel}}"
  when: ansible_os_family=="RedHat"
- name: service enable and start
  service:
    name: "{{apache_package}}"
    state: started
    enabled: yes
- name: test by print
  debug:
    msg: "This is for testing"
  notify: restart rhel apache
  when: ansible_os_family=="RedHat"
  